{
 "title": "Factorio",
 "time": { "from": "2025-08-29T05:43:24.682Z", "to": "2025-08-31T18:48:51.955Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Killed by enemies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(entity) (factorio_kills{force=\"player\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Killed by players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by(entity) (factorio_kills{force!=\"player\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The big smoke",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(surface) (factorio_pollution)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Smoke generation rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum by(surface) (rate(factorio_pollution_produced[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deaths by player",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name) (factorio_player_deaths{name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Players",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "factorio_players_connected", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Deaths :(",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by() (factorio_player_deaths{name!=\"\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Rockets launched",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(force, surface) (factorio_rockets_launched{force!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pave the Planet!",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(surface, tile) (factorio_area_paved{surface!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Researches finished",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(force) (factorio_researches_finished{force!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evolution",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(surface) (factorio_evolution)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most Dead 👍👍",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum by(name) (factorio_player_deaths{name!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}